#https://confluence.ozon.ru/display/ITDOC/Gitlab%3A+Common+pipeline
include: 'https://gitlab.ozon.ru/pub/ci/raw/0.0.3/.common.gitlab-ci.yml'

variables:
  # свой namespace, по умолчанию берется $CI_PROJECT_NAMESPACE
  K8S_NAMESPACE: $CI_PROJECT_NAMESPACE
  # если не указать будет использоваться $CI_PROJECT_PATH_SLUG (формат group-subgroup-project, например cas-roles)
  SERVICE_NAME: overload-fe
  # Проект в JIRA в котором будут заводится релизы
  JIRA_PROJ: LOAD
  # Префикс для релиза в jira
  JIRA_VERSION_PREFIX: release/
  # Путь до файлов values
  HELM_VALUES_FOLDER: .o3/k8s
  # Расположение файла для сборки docker образа
  DOCKERFILE_PATH: .o3/build/package/Dockerfile

staging:
  when: on_success
